# Generated by Django 5.0.4 on 2024-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField(default=0)),
                ('published_on', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
