# Generated by Django 5.0.4 on 2024-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
