# Generated by Django 5.0.4 on 2024-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label',
            field=models.BooleanField(default=False),
        ),
    ]
